FEATURE_GROUPS_PLSDA = {
    "Atomic weight": "Basic Atomic Properties",
    "Atomic number": "Basic Atomic Properties",
    "Period": "Basic Atomic Properties",
    "Group": "Basic Atomic Properties",
    "quantum  number l": "Basic Atomic Properties",
    "Metal(1)/ metalloid(2)/ nonmetal(3)": "Basic Atomic Properties",
    "Mendeleev number": "Basic Atomic Properties",
    "Families": "Basic Atomic Properties",
    "valence s": "Valence Properties",
    "valence p": "Valence Properties",
    "valence d": "Valence Properties",
    "valence f": "Valence Properties",
    "unfilled s": "Valence Properties",
    "unfilled p": "Valence Properties",
    "unfilled d": "Valence Properties",
    "unfilled f": "Valence Properties",
    "no. of  valence  electrons": "Valence Properties",
    "outer shell electrons": "Valence Properties",
    "Gilman no. of valence electrons": "Valence Properties",
    "Metallic  valence": "Valence Properties",
    "Zeff": "Basic Atomic Properties",
    "1st Bohr radius (a0)": "Atomic & Ionic Radii",
    "Ionization energy (eV)": "Electronegativity & Electron Affinity",
    "Electron affinity (ev)": "Electronegativity & Electron Affinity",
    "Pauling EN": "Electronegativity & Electron Affinity",
    "Martynov Batsanov EN": "Electronegativity & Electron Affinity",
    "Mulliken EN": "Electronegativity & Electron Affinity",
    "Allred EN": "Electronegativity & Electron Affinity",
    "Allred Rockow EN": "Electronegativity & Electron Affinity",
    "Nagle EN": "Electronegativity & Electron Affinity",
    "Ghosh EN": "Electronegativity & Electron Affinity",
    "Atomic radius calculated": "Atomic & Ionic Radii",
    "Covalent radius": "Atomic & Ionic Radii",
    "Ionic radius": "Atomic & Ionic Radii",
    "Effective ionic radius": "Atomic & Ionic Radii",
    "Miracle radius": "Atomic & Ionic Radii",
    "van der Waals radius": "Atomic & Ionic Radii",
    "Zunger radii sum": "Atomic & Ionic Radii",
    "Crystal radius": "Atomic & Ionic Radii",
    "Covalent CSD radius": "Atomic & Ionic Radii",
    "Slater radius": "Atomic & Ionic Radii",
    "Orbital radius": "Atomic & Ionic Radii",
    "Pauling, R(CN12)": "Atomic & Ionic Radii",
    "Pauling, R(1)": "Atomic & Ionic Radii",
    "polarizability, A^3": "Themal & Physical Properties",
    "Melting point, K": "Themal & Physical Properties",
    "Boiling point, K": "Themal & Physical Properties",
    "Density,  g/mL": "Themal & Physical Properties",
    "Specific heat, J/g K": "Themal & Physical Properties",
    "Heat of fusion,  kJ/mol": "Themal & Physical Properties",
    "Heat of vaporization,  kJ/mol": "Themal & Physical Properties",
    "Heat of atomization,  kJ/mol": "Themal & Physical Properties",
    "Thermal conductivity, W/m K": "Themal & Physical Properties",
    "Cohesive  energy": "Themal & Physical Properties",
    "Bulk modulus, GPa": "Themal & Physical Properties",
    "DFT LDA Etot": "DFT LDA & LSD Properties",
    "DFT LDA Ekin": "DFT LDA & LSD Properties",
    "DFT LDA Ecoul": "DFT LDA & LSD Properties",
    "DFT LDA Eenuc": "DFT LDA & LSD Properties",
    "DFT LDA Exc": "DFT LDA & LSD Properties",
    "DFT LSD Etot": "DFT LDA & LSD Properties",
    "DFT LSD Ekin": "DFT LDA & LSD Properties",
    "DFT LSD Ecoul": "DFT LDA & LSD Properties",
    "DFT LSD Eenuc": "DFT LDA & LSD Properties",
    "DFT LSD Exc": "DFT LDA & LSD Properties",
    "DFT RLDA Etot": "DFT RLDA & ScRLDA Properties",
    "DFT RLDA Ekin": "DFT RLDA & ScRLDA Properties",
    "DFT RLDA Ecoul": "DFT RLDA & ScRLDA Properties",
    "DFT RLDA Eenuc": "DFT RLDA & ScRLDA Properties",
    "DFT RLDA Exc": "DFT RLDA & ScRLDA Properties",
    "DFT ScRLDA Etot": "DFT RLDA & ScRLDA Properties",
    "DFT ScRLDA Ekin": "DFT RLDA & ScRLDA Properties",
    "DFT ScRLDA Ecoul": "DFT RLDA & ScRLDA Properties",
    "DFT ScRLDA Eenuc": "DFT RLDA & ScRLDA Properties",
    "DFT ScRLDA Exc": "DFT RLDA & ScRLDA Properties",
    "Neutron Cross Section": "Themal & Physical Properties",
}
